services:
  backend-for-frontend:
    build:
      context: services/backend-for-frontend-nodejs
      dockerfile: Dockerfile
    image: backend-for-frontend-nodejs:latest
    ports:
      - "10115:10114"
    environment:
      - MY_SERVICE=backend-for-frontend

  meminator:
    build:
      context: services/meminator-${PROGRAMMING_LANGUAGE}
      dockerfile: Dockerfile
    image: ${IMAGE_REPO_USER}/meminator-${PROGRAMMING_LANGUAGE}:${WORKSHOP_VERSION}
    ports:
      - "10116:10114" # they can't be the same
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT
      - OTEL_EXPORTER_OTLP_HEADERS
      - OTEL_SERVICE_NAME=meminator-${PROGRAMMING_LANGUAGE}

  phrase-picker:
    build:
      context: services/phrase-picker-${PROGRAMMING_LANGUAGE}
      dockerfile: Dockerfile
    image: ${IMAGE_REPO_USER}/phrase-picker-${PROGRAMMING_LANGUAGE}:${WORKSHOP_VERSION}
    ports:
      - "10117:10114" # the outer ports can't be the same
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT
      - OTEL_EXPORTER_OTLP_HEADERS
      - OTEL_SERVICE_NAME=phrase-picker-${PROGRAMMING_LANGUAGE}

  image-picker:
    build:
      context: services/image-picker-${PROGRAMMING_LANGUAGE}
      dockerfile: Dockerfile
    image: ${IMAGE_REPO_USER}/image-picker-${PROGRAMMING_LANGUAGE}:${WORKSHOP_VERSION}
    ports:
      - "10118:10114" # the outer ports can't be the same
    environment:
      - BUCKET_NAME
      - OTEL_EXPORTER_OTLP_ENDPOINT
      - OTEL_EXPORTER_OTLP_HEADERS
      - OTEL_SERVICE_NAME=image-picker-${PROGRAMMING_LANGUAGE}

  web:
    build:
      context: services/web
      dockerfile: Dockerfile
      args:
        HONEYCOMB_API_KEY: ${HONEYCOMB_API_KEY}
    image: ${IMAGE_REPO_USER}/web:${WORKSHOP_VERSION}
    # volumes: # uncomment this for faster development on the frontend
    #   - ./services/web/dist:/usr/share/nginx/html # Mount directory containing static files -- only do this for development
    ports:
      - "8080:80" # Expose port 8080 for Nginx